/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: applikethat === */

  export namespace applikethat {
  
    /* --- enums --- */
    /* (none) */
  
    /* --- tables --- */
    /* (none) */
  
    /* --- aggregate types --- */
  
    // `never` rather than `any` types would be more accurate in this no-tables case, but they stop `shortcuts.ts` compiling
  
    export type Table = never;
    export type Selectable = never;
    export type JSONSelectable = never;
    export type Whereable = never;
    export type Insertable = never;
    export type Updatable = never;
    export type UniqueIndex = never;
    export type Column = never;
  
    export type AllBaseTables = [];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [];
  }


  /* === global aggregate types === */

  export type Schema = 'applikethat';
  export type Table = applikethat.Table;
  export type Selectable = applikethat.Selectable;
  export type JSONSelectable = applikethat.JSONSelectable;
  export type Whereable = applikethat.Whereable;
  export type Insertable = applikethat.Insertable;
  export type Updatable = applikethat.Updatable;
  export type UniqueIndex = applikethat.UniqueIndex;
  export type Column = applikethat.Column;

  export type AllSchemas = ['applikethat'];
  export type AllBaseTables = [...applikethat.AllBaseTables];
  export type AllForeignTables = [...applikethat.AllForeignTables];
  export type AllViews = [...applikethat.AllViews];
  export type AllMaterializedViews = [...applikethat.AllMaterializedViews];
  export type AllTablesAndViews = [...applikethat.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = any;

  export type JSONSelectableForTable<T extends Table> = any;

  export type WhereableForTable<T extends Table> = any;

  export type InsertableForTable<T extends Table> = any;

  export type UpdatableForTable<T extends Table> = any;

  export type UniqueIndexForTable<T extends Table> = any;

  export type ColumnForTable<T extends Table> = any;

  export type SQLForTable<T extends Table> = any;

}
