/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: myapp === */

  export namespace myapp {
  
    /* --- enums --- */
    /* (none) */
  
    /* --- tables --- */
    /* (none) */
  
    /* --- aggregate types --- */
  
    // `never` rather than `any` types would be more accurate in this no-tables case, but they stop `shortcuts.ts` compiling
  
    export type Table = never;
    export type Selectable = never;
    export type JSONSelectable = never;
    export type Whereable = never;
    export type Insertable = never;
    export type Updatable = never;
    export type UniqueIndex = never;
    export type Column = never;
  
    export type AllBaseTables = [];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [];
  }


  /* === global aggregate types === */

  export type Schema = 'myapp';
  export type Table = myapp.Table;
  export type Selectable = myapp.Selectable;
  export type JSONSelectable = myapp.JSONSelectable;
  export type Whereable = myapp.Whereable;
  export type Insertable = myapp.Insertable;
  export type Updatable = myapp.Updatable;
  export type UniqueIndex = myapp.UniqueIndex;
  export type Column = myapp.Column;

  export type AllSchemas = ['myapp'];
  export type AllBaseTables = [...myapp.AllBaseTables];
  export type AllForeignTables = [...myapp.AllForeignTables];
  export type AllViews = [...myapp.AllViews];
  export type AllMaterializedViews = [...myapp.AllMaterializedViews];
  export type AllTablesAndViews = [...myapp.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = any;

  export type JSONSelectableForTable<T extends Table> = any;

  export type WhereableForTable<T extends Table> = any;

  export type InsertableForTable<T extends Table> = any;

  export type UpdatableForTable<T extends Table> = any;

  export type UniqueIndexForTable<T extends Table> = any;

  export type ColumnForTable<T extends Table> = any;

  export type SQLForTable<T extends Table> = any;

}
